<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CopyToMods Condition="'$(CopyToMods)' == '' AND '$(Configuration)' == 'Debug'">true</CopyToMods>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ResonitePath)'==''">
    <ResonitePath>C:\Program Files (x86)\Steam\steamapps\common\Resonite\Headless\</ResonitePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ResoniteModLoader" Version="5.0.1" />
    <Reference Include="Elements.Core">
      <HintPath>$(ResonitePath)Elements.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SkyFrost.Base">
      <HintPath>$(ResonitePath)SkyFrost.Base.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SkyFrost.Base.Models">
      <HintPath>$(ResonitePath)SkyFrost.Base.Models.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FrooxEngine">
      <HintPath>$(ResonitePath)FrooxEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FrooxEngine.Store">
      <HintPath>$(ResonitePath)FrooxEngine.Store.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Elements.Assets">
      <HintPath>$(ResonitePath)Elements.Assets.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Elements.Quantity">
      <HintPath>$(ResonitePath)Elements.Quantity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Renderite.Shared">
      <HintPath>$(ResonitePath)Renderite.Shared.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Resonite">
      <HintPath>$(ResonitePath)Resonite.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(ResonitePath)Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(CopyToMods)' == 'true'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)" />
    <Message Text="Copied $(TargetFileName) to $(ModsPath)" Importance="high" />
  </Target>
</Project>
